
telegram:
  bot:
    token1: ${TELEGRAM_TOKEN1}
    id1: ${TELEGRAM_ID1}

    token2: ${TELEGRAM_TOKEN2}
    id2: ${TELEGRAM_ID2}

    token3: ${TELEGRAM_TOKEN3}
    id3: ${TELEGRAM_ID3}

    token4: ${TELEGRAM_TOKEN4}
    id4: ${TELEGRAM_ID4}
    topic41: ${TOPIC_4}

    token5: ${TELEGRAM_TOKEN5}
    id5: ${TELEGRAM_ID5}
    topic5: ${TOPIC_5}

    khotixs-token: ${KHTOIXS_TELEGRAM_TOKEN}
    khotixs-id: ${KHOTIXS_TELEGRAM_ID}
    khotixs-topic: ${KHTOIXS_TOPIC}

    flutter-token: ${FLUTTER_TELEGRAM_TOKEN}
    flutter-id: ${FLUTTER_TELEGRAM_ID}
    flutter-topic: ${FLUTTER_TOPIC}

spring:
  application:
    name: "ISTAD-LMS"
  profiles:
    active: dev
server:
  port: 8080